### ISSUE TITLE
テーマを決めよう

### ISSUE THREAD

**Issue by mrs1669** [p2hacks/teamR10#2]
- [ ] ハッカソンで作るもののテーマを決めよう!!

**Comment by KaitoKudou** [comment]
雪だるま対戦ゲームありですね。

**Comment by mrs1669** [comment]
Web版とiOS版作って、今話題のクロスプラットフォームで対戦できたら面白そう(^^;;

**Comment by KaitoKudou** [comment]
子供が母親のご機嫌とって、クリスマスプレゼントをゲットするゲーム！！！
